$(document).ready(function(){
   $('#signupform_productmanager').css({
       "position":"center",
       "backgroud-color":"bisque",
       "margin-top":"100px",
       "margin-left":"300px"
   }); 
   $('#signupform_accountingmanager').css({
       "position":"center",
       "backgroud-color":"bisque",
       "margin-top":"100px",
       "margin-left":"20px"
   }); 
});